qa8/Controllers/AnswerSheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using qa8.Data;
using qa8.Models;

namespace qa8.Controllers
{
    public class AnswerSheetController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnswerSheetController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AnswerSheet
        public async Task<IActionResult> Index()
        {
            return View(await _context.AnswerSheets.ToListAsync());
        }

        // GET: AnswerSheet/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answerSheet = await _context.AnswerSheets
                .SingleOrDefaultAsync(m => m.id == id);
            if (answerSheet == null)
            {
                return NotFound();
            }

            return View(answerSheet);
        }

        // GET: AnswerSheet/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AnswerSheet/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,userId,quizId,questionId,questionType,choiceText,answerId,answerText,dateSubmitted,feedBack,Iscorrect,second")] AnswerSheet answerSheet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(answerSheet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(answerSheet);
        }

        // GET: AnswerSheet/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answerSheet = await _context.AnswerSheets.SingleOrDefaultAsync(m => m.id == id);
            if (answerSheet == null)
            {
                return NotFound();
            }
            return View(answerSheet);
        }

        // POST: AnswerSheet/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,userId,quizId,questionId,questionType,choiceText,answerId,answerText,dateSubmitted,feedBack,Iscorrect,second")] AnswerSheet answerSheet)
        {
            if (id != answerSheet.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(answerSheet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnswerSheetExists(answerSheet.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(answerSheet);
        }

        // GET: AnswerSheet/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answerSheet = await _context.AnswerSheets
                .SingleOrDefaultAsync(m => m.id == id);
            if (answerSheet == null)
            {
                return NotFound();
            }

            return View(answerSheet);
        }

        // POST: AnswerSheet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var answerSheet = await _context.AnswerSheets.SingleOrDefaultAsync(m => m.id == id);
            _context.AnswerSheets.Remove(answerSheet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnswerSheetExists(int id)
        {
            return _context.AnswerSheets.Any(e => e.id == id);
        }
    }
}

qa8/Controllers/IdeaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using qa8.Data;
using qa8.Models;
using qa8.Repository;

namespace qa8.Controllers
{
    [Authorize]
    public class IdeaController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        //----------------------------------------------------------------------

        public IdeaController(
            ApplicationDbContext context, 
            IHostingEnvironment hostingEnvironment,
            UserManager<ApplicationUser> userManager
            )
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
        }

        //--------------------
        public string NameSort { get; set; }
        public string DateSort { get; set; }
        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }
        // GET: Idea
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //// khu vuc danh cho cap 4
            var controllerPolicy = 4;

            var AccountPolicy = new AccountPolicy();
            var current_User = await _userManager.GetUserAsync(HttpContext.User);
            //check
            var check = AccountPolicy.CheckAccountLevelVsControllerPolicy(current_User, controllerPolicy);
            if (check)
            {
                ViewData["CurrentSort"] = sortOrder;
                ViewData["DateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_increase" : "";
                ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                ViewData["CurrentFilter"] = searchString;

                var ideas = from s in _context.Idea
                                  select s;
                if (!String.IsNullOrEmpty(searchString))
                {
                    ideas = ideas.Where(s => s.idea_Title.Contains(searchString)
                                           || Convert.ToDateTime(s.date_Created) >= Convert.ToDateTime(searchString));
                }

                switch (sortOrder)
                {
                    case "date_increase":
                        ideas = ideas.OrderBy(s => s.date_Created);
                        break;
                    case "Name":
                        ideas = ideas.OrderBy(s => s.idea_Title);
                        break;
                    case "name_desc":
                        ideas = ideas.OrderByDescending(s => s.idea_Title);
                        break;
                    default:
                        ideas = ideas.OrderByDescending(s => s.date_Created);
                        break;
                }
                int pageSize = 10;
                return View(await PaginatedList<Idea>.CreateAsync(ideas.AsNoTracking(), page ?? 1, pageSize));

                //return View(await _context.Idea.ToListAsync());
            }
            return View("~/Views/Account/AccessDenied.cshtml");
            
        }

        // GET: Idea/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //// khu vuc danh cho cap 4
            var controllerPolicy = 4;

            var AccountPolicy = new AccountPolicy();
            var current_User = await _userManager.GetUserAsync(HttpContext.User);
            //check
            var check = AccountPolicy.CheckAccountLevelVsControllerPolicy(current_User, controllerPolicy);
            if (check)
            {
                var idea = await _context.Idea
                .SingleOrDefaultAsync(m => m.id == id);
                if (idea == null)
                {
                    return NotFound();
                }

                return View(idea);
            }
            return View("~/Views/Account/AccessDenied.cshtml");

            
        }
        [AllowAnonymous]
        // GET: Idea/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Idea/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,idea_Title,idea_Content,date_Created,ip_Created")] Idea idea)
        {

            idea.date_Created = DateTime.Now.ToString();
            

            if (ModelState.IsValid)
            {
                _context.Add(idea);
                await _context.SaveChangesAsync();
                return View("~/Views/Idea/Thankyou.cshtml");
                //return RedirectToAction(nameof(Index));
            }
            return View(idea);
        }

        // GET: Idea/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var idea = await _context.Idea.SingleOrDefaultAsync(m => m.id == id);
        //    if (idea == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(idea);
        //}

        // POST: Idea/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("id,idea_Title,idea_Content,date_Created,ip_Created")] Idea idea)
        //{
        //    if (id != idea.id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(idea);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!IdeaExists(idea.id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(idea);
        //}

        // GET: Idea/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //// khu vuc danh cho cap 5
            var controllerPolicy = 5;

            var AccountPolicy = new AccountPolicy();
            var current_User = await _userManager.GetUserAsync(HttpContext.User);
            //check
            var check = AccountPolicy.CheckAccountLevelVsControllerPolicy(current_User, controllerPolicy);
            if (check)
            {
                var idea = await _context.Idea
                .SingleOrDefaultAsync(m => m.id == id);
                if (idea == null)
                {
                    return NotFound();
                }

                return View(idea);
            }
            return View("~/Views/Account/AccessDenied.cshtml");

            
        }

        // POST: Idea/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var idea = await _context.Idea.SingleOrDefaultAsync(m => m.id == id);
            _context.Idea.Remove(idea);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IdeaExists(int id)
        {
            return _context.Idea.Any(e => e.id == id);
        }

        public static string GetLocalIPAddress()
        {
            var host = Dns.GetHostEntry(Dns.GetHostName());
            foreach (var ip in host.AddressList)
            {
                if (ip.AddressFamily == AddressFamily.InterNetwork)
                {
                    return ip.ToString();
                }
            }
            throw new Exception("No network adapters with an IPv4 address in the system!");
        }

       
    }
}

qa8/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using qa8.Data;
using qa8.Models;
using qa8.Repository;


namespace qa8.Controllers
{
    [Authorize]
    public class ManagementController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        //----------------------------------------------------------------------

        public ManagementController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IHostingEnvironment hostingEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }
        public async Task<IActionResult> Index()
        {

            //// khu vuc danh cho cap 2
            var controllerPolicy = 2;

            var AccountPolicy = new AccountPolicy();
            var current_User = await _userManager.GetUserAsync(HttpContext.User);
            //check
            var check = AccountPolicy.CheckAccountLevelVsControllerPolicy(current_User, controllerPolicy);
            if (check)
            {
                return View();
            }
            return View("~/Views/Account/AccessDenied.cshtml");

            
        }
    }
}

qa8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Q&A System</title>

    <environment include="Development">
        @*<link href="~/lib/bootstrap-4.1.2-dist/css/bootstrap.min.css" rel="stylesheet" />*@
        <link href="~/lib/MDB-Free_4.5.9/css/bootstrap.min.css" rel="stylesheet" />
        @*<link href="~/lib/MDB-Free_4.5.9/css/mdb.min.css" rel="stylesheet" />*@
        <link href="~/lib/fontawesome-free-5.1.1-web/css/fontawesome.min.css" rel="stylesheet" />
        <link href="~/lib/fontawesome-free-5.1.1-web/css/solid.min.css" rel="stylesheet" />
        @*<link href="~/lib/tempusdominus/tempusdominus.min.css" rel="stylesheet" />*@
        <link href="~/lib/gijgo-combined-1.9.10/css/gijgo.min.css" rel="stylesheet" />
        @*<link href="~/css/sweet-alert.css" rel="stylesheet" />*@
        <link href="~/css/pretty-checkbox.css" rel="stylesheet" />
        <link href="~/css/animateCSS.css" rel="stylesheet" />
        <link href="~/lib/intro.js-2.9.0/introjs.css" rel="stylesheet" />
        <link href="~/lib/intro.js-2.9.0/themes/introjs-modern.css" rel="stylesheet" />

        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="shortcut icon" href="~/images/favicon.ico" />
        @*<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
        asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
        asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />*@
        <link href="~/lib/MDB-Free_4.5.9/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/fontawesome-free-5.1.1-web/css/fontawesome.min.css" rel="stylesheet" />
        <link href="~/lib/fontawesome-free-5.1.1-web/css/solid.min.css" rel="stylesheet" />
        <link href="~/lib/gijgo-combined-1.9.10/css/gijgo.min.css" rel="stylesheet" />
        <link href="~/css/pretty-checkbox.css" rel="stylesheet" />
        <link href="~/css/animateCSS.css" rel="stylesheet" />
        <link href="~/lib/intro.js-2.9.0/introjs.css" rel="stylesheet" />
        <link href="~/lib/intro.js-2.9.0/themes/introjs-modern.css" rel="stylesheet" />

        <link rel="stylesheet" href="~/css/site.css" />

        @*<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:#b5edfc">
        <div class="container">
            <a id="help" class="navbar-brand " href="#" style="font-size:150%;font:600">Q&A System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active mr-1">
                        @*<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>*@
                        <a class="btn btn-outline-primary" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item mr-1">
                        @*<a id="testeditor" class="btn btn-outline-primary" asp-area="" asp-controller="Quiz" asp-action="Index">Management</a>*@
                        <a id="testeditor" class="btn btn-outline-primary" asp-area="" asp-controller="Management" asp-action="Index">Management</a>
                    </li>
                    @*<li class="nav-item mr-1">
                        <a id="ideacreate" class="btn btn-outline-primary " asp-area="" asp-controller="Idea" asp-action="Create">Idea</a>
                    </li>*@
                    <li class="nav-item mr-1">
                        <a id="dothetest" class="btn btn-outline-primary" asp-area="" asp-controller="Quiz" asp-action="SelectQuiz">Test</a>
                    </li>


                    @*<li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="AnswerSheet" asp-action="Index">AnswerSheet</a>
        </li>*@

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>



    <div class="container body-content">
        @RenderBody()

        <footer>
            <p>&copy; 2018 - SHC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/popperjs/popper.js"></script>
        <script src="~/lib/bootstrap-4.1.2-dist/js/bootstrap.min.js"></script>

        <script src="~/lib/intro.js-2.9.0/intro.js"></script>
        <script src="~/lib/momentjs/moment.min.js"></script>

        <script src="~/lib/gijgo-combined-1.9.10/js/gijgo.min.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/popperjs/popper.js"></script>
        <script src="~/lib/bootstrap-4.1.2-dist/js/bootstrap.min.js"></script>

        <script src="~/lib/intro.js-2.9.0/intro.js"></script>
        <script src="~/lib/momentjs/moment.min.js"></script>

        <script src="~/lib/gijgo-combined-1.9.10/js/gijgo.min.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>*@
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>