qa8/Models/Question.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using qa8.Models;

namespace qa8.Models
{
    
    public class Question
    {
        public enum Correct
        {
            A, B, C, D, E
        }
        [Display(Name = "Code")]
        public int id { get; set; }

        [Display(Name = "QuizID")]
        public int quizId { get; set; }

        [Display(Name = "Question")]
        public string text { get; set; }

        [Display(Name = "Choice A")]
        public string A { get; set; }

        [Display(Name = "Choice B")]
        public string B { get; set; }

        [Display(Name = "Choice C")]
        public string C { get; set; }

        [Display(Name = "Choice D")]
        public string D { get; set; }

        [Display(Name = "Choice E")]
        public string E { get; set; }


        [Display(Name = "Correct")]
        public Correct correct { get; set; }

        [Display(Name = "Answer choice")]
        public bool multipleChoice { get; set; }

        [Display(Name = "Question image")]
        public string imageSource { get; set; }



        public string imageSourceA { get; set; }
        public string imageSourceB { get; set; }
        public string imageSourceC { get; set; }
        public string imageSourceD { get; set; }
        public string imageSourceE { get; set; }


        public Quiz quiz { get; set; }
        public IEnumerable<AnswerSheet> answerSheets { get; set; }

    }
}

qa8/Controllers/QuizController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Npoi.Core.SS.UserModel;
using Npoi.Core.XSSF.UserModel;
using qa8.Data;
using qa8.Extensions;
using qa8.Models;
using qa8.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using qa8.Repository;
using System.Diagnostics;

namespace qa8.Controllers
{
    public class QuizController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        //----------------------------------------------------------------------

        public QuizController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager, 
            IHostingEnvironment hostingEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        //----------------------------------------------------------------------

        const string UserConnected = "UserConnected";
        const string SelectedQuiz = "SelectedQuiz";
        const string quizId = "quizId";
        

        //---------upload an image----------------------------------------------------
        public string UploadImage(string fullName, IFormFile image)
        {
            string fileName = "";
            if (image != null)
            {
                fileName = Path.Combine(_hostingEnvironment.WebRootPath, Path.GetFileName(image.FileName));
                image.CopyTo(new FileStream(fileName, FileMode.Create));

            }
            return fileName;
        }
        //------getallanswersheethavingsamequizId-----------------------------------------------------------------
        public async Task<List<AnswerSheet>> GetAllAnswerSheetHavingSameQuizID(int id)
        {
            var listOfAnswerSheet = await _context.AnswerSheets.Where(q => q.quizId.Equals(id)).AsNoTracking().ToListAsync();
            return listOfAnswerSheet;
        }
        //----------get a answersheet---------------------------------------------
        public async Task<AnswerSheet> GetAAnswerSheetInformation(AnswerSheet answerSheet)
        {
            var answerSheetInfo = await _context.AnswerSheets.Where(q => q.quizId.Equals(answerSheet.quizId) && q.userId.Equals(answerSheet.userId) && q.questionId.Equals(answerSheet.questionId)).AsNoTracking().FirstOrDefaultAsync();
            return answerSheetInfo;
        }
        //----------get a quiz -----------------------------------
        public async Task<Quiz> GetAQuizInformation(int id)
        {
            var quiz = await _context.Quizzes.Where(q => q.id.Equals(id)).AsNoTracking().SingleOrDefaultAsync();
            return quiz;
        }
        public async Task<List<Participant>> GetListOfPariticipants(int id)
        {
            var listOfParticipants = await _context.Participants.Where(q => q.quizId.Equals(id)).ToListAsync();
            return listOfParticipants;
        }
        //----------make a question list---------------------------------------------------
        public async Task<List<Question>> GetAQuestionsList(int id)
        {
            List<Question> questionslist = await _context.Questions
                     .Where(q => q.quizId.Equals(id))
                     .AsNoTracking()
                     .ToListAsync();
            return questionslist;
        }
        //------------------------------------------------------Module

        // GET: Quiz
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //return View(await _context.Quizzes.ToListAsync());
            //// khu vuc danh cho cap 2
            var controllerPolicy = 2;

            var AccountPolicy = new AccountPolicy();
            var current_User = await _userManager.GetUserAsync(HttpContext.User);
            //check
            var check = AccountPolicy.CheckAccountLevelVsControllerPolicy(current_User, controllerPolicy);
                    if (check)
                    {
                                ViewData["CurrentSort"] = sortOrder;
                                ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                                ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
                                if (searchString != null)
                                {
                                        page = 1;
                                }
                                else
                                {
                                        searchString = currentFilter;
                                }
                                ViewData["CurrentFilter"] = searchString;

                                var quizContext = from s in _context.Quizzes
                                                  select s;
                                if (!String.IsNullOrEmpty(searchString))
                                {
                                        quizContext = quizContext.Where(s => s.text.Contains(searchString)
                                                               || s.id.ToString().Contains(searchString));
                                }

                                switch (sortOrder)
                                {
                                        case "name_desc":
                                            quizContext = quizContext.OrderByDescending(s => s.text);
                                            break;
                                        case "Date":
                                            quizContext = quizContext.OrderBy(s => s.id);
                                            break;
                                        case "date_desc":
                                            quizContext = quizContext.OrderByDescending(s => s.id);
                                            break;
                                        default:
                                            quizContext = quizContext.OrderBy(s => s.text);
                                            break;
                                }
                                int pageSize = 15;
                                return View(await PaginatedList<Quiz>.CreateAsync(quizContext.AsNoTracking(), page ?? 1, pageSize));
                                //return View(await _context.Quizzes.ToListAsync());
                    }
            return View("~/Views/Account/AccessDenied.cshtml");

            
        }


        //----------------------------------------------------------------------
        //get quiz name

       



        //---Why we need this savedata1 . receive answer from client side----------------------------------------------------------------
        [HttpPost]
        public async Task<JsonResult> SaveData1(string data)
        {

            AnswerSheetVM answerSheetVM = JsonConvert.DeserializeObject<AnswerSheetVM>(data);
            //chuyển đổi dữ liệu thô thành dữ liệu xài được
            var questionslength = answerSheetVM.questions.Count();
            var currentDateTime = DateTime.Now.ToString("G", CultureInfo.CreateSpecificCulture("en-us"));
            List<AnswerSheet> answerSheets = new List<AnswerSheet>();
            List<int> ListOfAnswerSheetQuestionIdInDatabase = new List<int>();
            ListOfAnswerSheetQuestionIdInDatabase = await GetAListOfAnswerSheetQuestionID(answerSheetVM.questions[0]);
            ListOfAnswerSheetQuestionIdInDatabase.Sort();
            var questionListOfThisQuiz = await GetAQuestionsList(answerSheetVM.quiz.id);
            
            for (var i = 0 ; i < questionslength ; i++)
            {
                AnswerSheet answerSheet = new AnswerSheet();
                answerSheet.dateSubmitted = currentDateTime;
                answerSheet.quizId = answerSheetVM.quiz.id;
                answerSheet.questionId = answerSheetVM.questions[i].id;
                answerSheet.userId = answerSheetVM.questions[i].userId;
                answerSheet.questionType = answerSheetVM.questions[i].multiplechoice;
                answerSheet.second = answerSheetVM.cycletime[i+1];
                if (answerSheetVM.questions[i].multiplechoice)
                {
                    answerSheet.answerText = answerSheetVM.selections[i];
                    answerSheet.correctAnswer = answerSheetVM.questions[i].correctAnswer;
                    if (answerSheet.answerText == answerSheet.correctAnswer)
                    {
                        answerSheet.isCorrect = true;
                    }
                    else
                    {
                        answerSheet.isCorrect = false;
                    }
                }
                else
                {
                    answerSheet.openAnswer = answerSheetVM.selections[i];
                }
                //cho vào 1 cái list
                answerSheets.Add(answerSheet);
            }
            bool status = false;
            string message = string.Empty;
            //kiểm tra tồn tại kết quả trước khi lưu vào cơ sở dữ liệu
            var answerSheetslength = answerSheets.Count();
            for (var j = 0; j < answerSheetslength; j++)
            {
                var check = ListOfAnswerSheetQuestionIdInDatabase.Contains(answerSheets[j].questionId);
                if (check == false)
                {
                    try
                    {
                        _context.Add(answerSheets[j]);

qa8/Views/Question/Delete.cshtml
@model qa8.Models.Question

@{
    ViewData["Title"] = "Q&A System";
}

@*<h2 class="text-danger" style="text-align:center">Delete question</h2>*@
<h3 class="text-danger" >Are you sure you want to delete this?</h3>
<div >
    <form class="form-horizontal col-sm-6">
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.id)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.id)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.text)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.text)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.A)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.A)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.B)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.B)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.C)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.C)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.D)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.D)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.E)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.E)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.correct)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.correct)">
            </div>
        </div>
        
       
    </form>
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a class="btn btn-outline-warning" asp-controller="Quiz" asp-action="Details" asp-route-id="@ViewBag.quizId">Cancel</a>
    </form>
</div>

qa8/Views/Question/Details.cshtml
@model qa8.Models.Question

@{
    ViewData["Title"] = "Q&A System";
}

<h2 class="text-success">Details</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.quizId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.quizId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.multipleChoice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.multipleChoice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.A)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.A)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.B)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.B)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.C)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.C)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.D)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.D)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-controller="Quiz" asp-action="Details" asp-route-id="@ViewBag.quizId">Back to List</a>
</div>

qa8/Views/Question/Edit.cshtml
@model qa8.Models.Question

@{
    ViewData["Title"] = "Q&A System";
}

<h2 class="text-success" style="text-align:center">Edit your question</h2>

<div class="container" style="max-width:600px;padding:10px;background:#ebeff2">
    <form class="form-horizontal" role="form" asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row" style="padding-top:5px">
            @*<label class="control-label col-sm-3">Quiz name</label>
            <div class=" col-sm-8">
                <input disabled class="form-control" value="@ViewData["quizText"]" />
            </div>*@
            <input asp-for="quizId" value="@ViewData["quizId"]" class="form-control" type="hidden" />
        </div>
        <!---------------------------------------------------->
        <div class="row" style="padding-top:5px">
            <label asp-for="text" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8">
                <input asp-for="text" class="form-control " />
                <span asp-validation-for="text" class="text-danger"></span>
            </div>
        </div>
        <div class="row" style="padding-top:5px">
            <label class="col-form-label col-sm-3">Question image</label>

            <div class="col-sm-3">
                <input type="file" id="uploadImageQuestion" name="uploadImageQuestion" class="form-control" />
            </div>
            <div class="col-sm-6" id="cardImageQuestion" >
                <div class="card" style="width: 10rem;text-align:center">
                    <img class="card-img-top" src="~/images/adidas23701.jpg" id="srcImageQuestion">
                </div>
                @*<input class="btn btn-outline-danger" type="button" id="btnRemoveImageQuestion" value="Remove" />*@
                <input asp-for="imageSource"  class="form-control" id="txtImageQuestion" hidden />
            </div>
        </div>

        <!------------------------------------------------------>
        <div class="row" style="padding-top:5px">
            <label asp-for="A" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8">
                <input asp-for="A" class="form-control " />
                <span asp-validation-for="A" class="text-danger"></span>
            </div>
        </div>
        <div class="row" style="padding-top:5px">
            <label class="col-form-label col-sm-3">Image A</label>
            <div class="col-sm-3">
                <input type="file" id="uploadImageA" name="files" class="form-control" />
            </div>
            <div class="col-sm-6" id="cardImageSourceA" hidden>
                <div class="card" style="width: 10rem;text-align:center">
                    <img class="card-img-top" src="~/images/adidas23701.jpg" id="srcImageSourceA">
                </div>
                @*<input class="btn btn-outline-danger" type="button" id="btnRemoveImageSourceA" value="Remove" />*@
                <input asp-for="imageSourceA" value="" class="form-control" id="txtImageSourceA" hidden />
            </div>
        </div>
        <!------------------------------------------------>
        <div class="row" style="padding-top:5px">
            <label asp-for="B" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8">
                <input asp-for="B" class="form-control " />
                <span asp-validation-for="B" class="text-danger"></span>
            </div>
        </div>
        <div class="row" style="padding-top:5px">
            <label class="col-form-label col-sm-3">Image B</label>
            <div class="col-sm-3">
                <input type="file" id="uploadImageB" name="files" class="form-control" />
            </div>
            <div class="col-sm-6" id="cardImageSourceB" hidden>
                <div class="card" style="width: 10rem;text-align:center">
                    <img class="card-img-top" src="~/images/adidas23701.jpg" id="srcImageSourceB">
                </div>
                @*<input class="btn btn-outline-danger" type="button" id="btnRemoveImageSourceB" value="Remove" />*@
                <input asp-for="imageSourceB" value="" class="form-control" id="txtImageSourceB" hidden />
            </div>
        </div>
        <!--------------------------------------------->
        <div class="row" style="padding-top:5px">
            <label asp-for="C" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8">
                <input asp-for="C" class="form-control " />
                <span asp-validation-for="C" class="text-danger"></span>
            </div>
        </div>
        <div class="row" style="padding-top:5px">
            <label class="col-form-label col-sm-3">Image C</label>
            <div class="col-sm-3">
                <input type="file" id="uploadImageC" name="files" class="form-control" />
            </div>
            <div class="col-sm-6" id="cardImageSourceC" hidden>
                <div class="card" style="width: 10rem;text-align:center">
                    <img class="card-img-top" src="~/images/adidas23701.jpg" id="srcImageSourceC">
                </div>
                @*<input class="btn btn-outline-danger" type="button" id="btnRemoveImageSourceC" value="Remove" />*@
                <input asp-for="imageSourceC" value="" class="form-control" id="txtImageSourceC" hidden />
            </div>
        </div>
        <!-------------------------------------->
        <div class="row" style="padding-top:5px">
            <label asp-for="D" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8">
                <input asp-for="D" class="form-control " />
                <span asp-validation-for="D" class="text-danger"></span>
            </div>
        </div>
        <div class="row" style="padding-top:5px">
            <label class="col-form-label col-sm-3">Image D</label>
            <div class="col-sm-3">
                <input type="file" id="uploadImageD" name="files" class="form-control" />
            </div>
            <div class="col-sm-6" id="cardImageSourceD" hidden>
                <div class="card" style="width: 10rem;text-align:center">
                    <img class="card-img-top" src="~/images/adidas23701.jpg" id="srcImageSourceD">
                </div>
                @*<input class="btn btn-outline-danger" type="button" id="btnRemoveImageSourceD" value="Remove" />*@
                <input asp-for="imageSourceD" value="" class="form-control" id="txtImageSourceD" hidden />
            </div>
        </div>
        <!-------------------------------------->
        <div class="row" style="padding-top:5px">
            <label asp-for="E" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8">
                <input asp-for="E" class="form-control " />
                <span asp-validation-for="E" class="text-danger"></span>
            </div>
        </div>
        <div class="row" style="padding-top:5px">
            <label class="col-form-label col-sm-3">Image E</label>
            <div class="col-sm-3">
                <input type="file" id="uploadImageE" name="files" class="form-control" />
            </div>
            <div class="col-sm-6" id="cardImageSourceE" hidden>
                <div class="card" style="width: 10rem;text-align:center">
                    <img class="card-img-top" src="~/images/adidas23701.jpg" id="srcImageSourceE">
                </div>
                @*<input class="btn btn-outline-danger" type="button" id="btnRemoveImageSourceE" value="Remove" />*@
                <input asp-for="imageSourceE" value="" class="form-control" id="txtImageSourceE" hidden />
            </div>
        </div>
        <!----------------------------------------->
        <div class="row" style="padding-top:5px">
            <label asp-for="correct" class="control-label col-sm-3"></label>
            <div class=" col-sm-8">
                <select asp-for="correct" asp-items="Html.GetEnumSelectList<qa8.Models.Question.Correct>()" class="form-control"></select>
                <span asp-validation-for="correct" class="text-danger"></span>
            </div>
        </div>
        <div class="row" style="padding-top:5px">
            <label asp-for="multipleChoice" class="control-label col-sm-3"></label>
            <div class="checkbox col-sm-8">
                <label>
                    <input asp-for="multipleChoice" /> @Html.DisplayNameFor(model => model.multipleChoice)
                </label>
            </div>
        </div>
        @*<div class="row" style="padding-top:5px">
            <label asp-for="imageSource" class="control-label col-sm-3"></label>
            <div class=" col-sm-8">
                <input asp-for="imageSource" class="form-control " />
                <span asp-validation-for="imageSource" class="text-danger"></span>
            </div>
        </div>*@
        <div class=" col-sm-offset-2 col-sm-8" style="padding-top:5px">
            <button type="submit" value="Edit" class="btn btn-outline-primary ">Save</button>
            <a class="btn btn-outline-warning" asp-controller="Quiz" asp-action="Details" asp-route-id="@ViewBag.quizId">Cancel</a>
        </div>
    </form>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

qa8/Views/Question/Index.cshtml
@model IEnumerable<qa8.Models.Question>

@{
    ViewData["Title"] = "Q&A System";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <a class="btn btn-success " asp-action="Create">New Question</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.A)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.B)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.C)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.D)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.correct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.multipleChoice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.imageSource)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quiz)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.text)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.A)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.B)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.C)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.D)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.correct)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.multipleChoice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.imageSource)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quiz.id)
                </td>
                <td>
                    <a class="btn btn-success fa fa-edit" asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                    <a class="btn btn-success fa fa-eye" asp-action="Details" asp-route-id="@item.id">Details</a> |
                    <a class="btn btn-danger fa fa-remove" title="Delete quiz" asp-route-id="@item.id">Delete</a>
                 </td>
            </tr>
        }
    </tbody>
</table>