qa8/Controllers/ParticipantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using qa8.Data;
using qa8.Models;
using qa8.Repository;

namespace qa8.Controllers
{
    [Authorize]
    public class ParticipantController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        public ParticipantController(
            ApplicationDbContext context
            , UserManager<ApplicationUser> userManager, 
            IHostingEnvironment hostingEnvironment
            )
        {
            _context = context;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Participant
        [Authorize]
        public async Task<IActionResult> Index()
        {
            //// khu vuc danh cho cap 2
            var controllerPolicy = 2;

            var AccountPolicy = new AccountPolicy();
            var current_User = await _userManager.GetUserAsync(HttpContext.User);
            //check
            var check = AccountPolicy.CheckAccountLevelVsControllerPolicy(current_User, controllerPolicy);
            if (check)
            {
                var applicationDbContext = _context.Participants.Include(p => p.quiz);
                return View(await applicationDbContext.ToListAsync());
            }
            return View("~/Views/Account/AccessDenied.cshtml");
            
        }

        // GET: Participant/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants
                .Include(p => p.quiz)
                .SingleOrDefaultAsync(m => m.id == id);
            if (participant == null)
            {
                return NotFound();
            }
            ViewData["quizId"] = participant.quizId;
            return View(participant);
        }

        // GET: Participant/Create
        [Authorize]
        public async Task<IActionResult> Create(int quizId)
        {
            Quiz quiz = await _context.Quizzes.Where(p => p.id == quizId).AsNoTracking().SingleAsync();

            ViewData["quizId"] = quiz.id;
            //ViewData["quizId"] = new SelectList(_context.Quizzes, "id", "id");
            ViewData["text"] = quiz.text;
            var s = ViewData["quizId"];
            return  View();
        }

        // POST: Participant/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("id,quizId,userId")] Participant participant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(participant);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("ParticipantsList", "Quiz", new { id = participant.quizId });
            }
            //ViewData["quizId"] = new SelectList(_context.Quizzes, "id", "id", participant.quizId);
            return View(participant);
        }

        // GET: Participant/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants.SingleOrDefaultAsync(m => m.id == id);
            if (participant == null)
            {
                return NotFound();
            }
            //ViewData["quizId"] = new SelectList(_context.Quizzes, "id", "id", participant.quizId);
            ViewData["quizId"] = participant.quizId;
            return View(participant);
        }

        // POST: Participant/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("id,quizId,userId")] Participant participant)
        {
            if (id != participant.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(participant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParticipantExists(participant.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("ParticipantsList", "Quiz", new { id = participant.quizId });
            }
            //ViewData["quizId"] = new SelectList(_context.Quizzes, "id", "id", participant.quizId);
            return View(participant);
        }

        // GET: Participant/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants
                .Include(p => p.quiz)
                .SingleOrDefaultAsync(m => m.id == id);
            if (participant == null)
            {
                return NotFound();
            }
            ViewData["quizId"] = participant.quizId;
            return View(participant);
        }

        // POST: Participant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participant = await _context.Participants.SingleOrDefaultAsync(m => m.id == id);
            _context.Participants.Remove(participant);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("ParticipantsList", "Quiz", new { id = participant.quizId });
        }

        private bool ParticipantExists(int id)
        {
            return _context.Participants.Any(e => e.id == id);
        }
    }
}

qa8/Controllers/QuizController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Npoi.Core.SS.UserModel;
using Npoi.Core.XSSF.UserModel;
using qa8.Data;
using qa8.Extensions;
using qa8.Models;
using qa8.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using qa8.Repository;
using System.Diagnostics;

namespace qa8.Controllers
{
    public class QuizController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        //----------------------------------------------------------------------

        public QuizController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager, 
            IHostingEnvironment hostingEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        //----------------------------------------------------------------------

        const string UserConnected = "UserConnected";
        const string SelectedQuiz = "SelectedQuiz";
        const string quizId = "quizId";
        

        //---------upload an image----------------------------------------------------
        public string UploadImage(string fullName, IFormFile image)
        {
            string fileName = "";
            if (image != null)
            {
                fileName = Path.Combine(_hostingEnvironment.WebRootPath, Path.GetFileName(image.FileName));
                image.CopyTo(new FileStream(fileName, FileMode.Create));

            }
            return fileName;
        }
        //------getallanswersheethavingsamequizId-----------------------------------------------------------------
        public async Task<List<AnswerSheet>> GetAllAnswerSheetHavingSameQuizID(int id)
        {
            var listOfAnswerSheet = await _context.AnswerSheets.Where(q => q.quizId.Equals(id)).AsNoTracking().ToListAsync();
            return listOfAnswerSheet;
        }
        //----------get a answersheet---------------------------------------------
        public async Task<AnswerSheet> GetAAnswerSheetInformation(AnswerSheet answerSheet)
        {
            var answerSheetInfo = await _context.AnswerSheets.Where(q => q.quizId.Equals(answerSheet.quizId) && q.userId.Equals(answerSheet.userId) && q.questionId.Equals(answerSheet.questionId)).AsNoTracking().FirstOrDefaultAsync();
            return answerSheetInfo;
        }
        //----------get a quiz -----------------------------------
        public async Task<Quiz> GetAQuizInformation(int id)
        {
            var quiz = await _context.Quizzes.Where(q => q.id.Equals(id)).AsNoTracking().SingleOrDefaultAsync();
            return quiz;
        }
        public async Task<List<Participant>> GetListOfPariticipants(int id)
        {
            var listOfParticipants = await _context.Participants.Where(q => q.quizId.Equals(id)).ToListAsync();
            return listOfParticipants;
        }
        //----------make a question list---------------------------------------------------
        public async Task<List<Question>> GetAQuestionsList(int id)
        {
            List<Question> questionslist = await _context.Questions
                     .Where(q => q.quizId.Equals(id))
                     .AsNoTracking()
                     .ToListAsync();
            return questionslist;
        }
        //------------------------------------------------------Module

        // GET: Quiz
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //return View(await _context.Quizzes.ToListAsync());
            //// khu vuc danh cho cap 2
            var controllerPolicy = 2;

            var AccountPolicy = new AccountPolicy();
            var current_User = await _userManager.GetUserAsync(HttpContext.User);
            //check
            var check = AccountPolicy.CheckAccountLevelVsControllerPolicy(current_User, controllerPolicy);
                    if (check)
                    {
                                ViewData["CurrentSort"] = sortOrder;
                                ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                                ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
                                if (searchString != null)
                                {
                                        page = 1;
                                }
                                else
                                {
                                        searchString = currentFilter;
                                }
                                ViewData["CurrentFilter"] = searchString;

                                var quizContext = from s in _context.Quizzes
                                                  select s;
                                if (!String.IsNullOrEmpty(searchString))
                                {
                                        quizContext = quizContext.Where(s => s.text.Contains(searchString)
                                                               || s.id.ToString().Contains(searchString));
                                }

                                switch (sortOrder)
                                {
                                        case "name_desc":
                                            quizContext = quizContext.OrderByDescending(s => s.text);
                                            break;
                                        case "Date":
                                            quizContext = quizContext.OrderBy(s => s.id);
                                            break;
                                        case "date_desc":
                                            quizContext = quizContext.OrderByDescending(s => s.id);
                                            break;
                                        default:
                                            quizContext = quizContext.OrderBy(s => s.text);
                                            break;
                                }
                                int pageSize = 15;
                                return View(await PaginatedList<Quiz>.CreateAsync(quizContext.AsNoTracking(), page ?? 1, pageSize));
                                //return View(await _context.Quizzes.ToListAsync());
                    }
            return View("~/Views/Account/AccessDenied.cshtml");

            
        }


        //----------------------------------------------------------------------
        //get quiz name

       



        //---Why we need this savedata1 . receive answer from client side----------------------------------------------------------------
        [HttpPost]
        public async Task<JsonResult> SaveData1(string data)
        {

            AnswerSheetVM answerSheetVM = JsonConvert.DeserializeObject<AnswerSheetVM>(data);
            //chuyển đổi dữ liệu thô thành dữ liệu xài được
            var questionslength = answerSheetVM.questions.Count();
            var currentDateTime = DateTime.Now.ToString("G", CultureInfo.CreateSpecificCulture("en-us"));
            List<AnswerSheet> answerSheets = new List<AnswerSheet>();
            List<int> ListOfAnswerSheetQuestionIdInDatabase = new List<int>();
            ListOfAnswerSheetQuestionIdInDatabase = await GetAListOfAnswerSheetQuestionID(answerSheetVM.questions[0]);
            ListOfAnswerSheetQuestionIdInDatabase.Sort();
            var questionListOfThisQuiz = await GetAQuestionsList(answerSheetVM.quiz.id);
            
            for (var i = 0 ; i < questionslength ; i++)
            {
                AnswerSheet answerSheet = new AnswerSheet();
                answerSheet.dateSubmitted = currentDateTime;
                answerSheet.quizId = answerSheetVM.quiz.id;
                answerSheet.questionId = answerSheetVM.questions[i].id;
                answerSheet.userId = answerSheetVM.questions[i].userId;
                answerSheet.questionType = answerSheetVM.questions[i].multiplechoice;
                answerSheet.second = answerSheetVM.cycletime[i+1];
                if (answerSheetVM.questions[i].multiplechoice)
                {
                    answerSheet.answerText = answerSheetVM.selections[i];
                    answerSheet.correctAnswer = answerSheetVM.questions[i].correctAnswer;
                    if (answerSheet.answerText == answerSheet.correctAnswer)
                    {
                        answerSheet.isCorrect = true;
                    }
                    else
                    {
                        answerSheet.isCorrect = false;
                    }
                }
                else
                {
                    answerSheet.openAnswer = answerSheetVM.selections[i];
                }
                //cho vào 1 cái list
                answerSheets.Add(answerSheet);
            }
            bool status = false;
            string message = string.Empty;
            //kiểm tra tồn tại kết quả trước khi lưu vào cơ sở dữ liệu
            var answerSheetslength = answerSheets.Count();
            for (var j = 0; j < answerSheetslength; j++)
            {
                var check = ListOfAnswerSheetQuestionIdInDatabase.Contains(answerSheets[j].questionId);
                if (check == false)
                {
                    try
                    {
                        _context.Add(answerSheets[j]);

qa8/Views/Quiz/Create.cshtml
@model qa8.Models.Quiz

@{
    ViewData["Title"] = "Q&A System";
}

<h2 class="text-success" style="text-align:center">Create new test</h2>

<div class="container" style="max-width:600px;padding:10px;background:#ebeff2">

    <form class="form-horizontal" role="form" asp-action="Create" autocomplete="off">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @*<div class="form-group">
                <label asp-for="quizId" class="control-label col-sm-3"></label>
                <div class="col-sm-8">
                    <input asp-for="quizId" class="form-control" id="quizName" placeholder="Enter quiz name">
                </div>
                <span asp-validation-for="quizId" class="text-danger"></span>
            </div>*@
        <div class="row">
            <label asp-for="text" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8" data-step="1" data-intro="Pick a name for your test">
                <input asp-for="text" class="form-control" id="quizName" placeholder="Input test name, example: 4M">
                <span asp-validation-for="text" class="text-danger"></span>
            </div>

        </div>
        @* ------------------- *@
        @*<div class="row">
                <label for="colFormLabel" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="colFormLabel" placeholder="col-form-label">
                </div>
            </div>*@
        @* ------------------- *@
        <div style="padding-top:5px" class="row">
            <label class="col-form-label col-sm-3">ID card No.</label>
            <div class="col-sm-8">
                <input disabled class="form-control" value="@ViewBag.authorId">
            </div>
            <input asp-for="authorId" value="@ViewBag.authorId" class="form-control" type="hidden">
        </div>

        <div style="padding-top:5px" class="row">
            <label asp-for="deadLine" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8" data-step="2" data-intro="Set deadline for this test">
                <input asp-for="deadLine" type="text" class="form-control" id="datetimepicker5"  autocomplete="false">
                @*<span asp-validation-for="deadLine" class="text-danger"></span>*@
            </div>
            @*<div class="col-sm-8" data-step="2" data-intro="Set deadline for this test">
                    <div class="form-group">
                        <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                            <input asp-for="deadLine" type="text" class="form-control datetimepicker-input" readonly="readonly"  data-target="#datetimepicker4" />
                            <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar-alt"></i></div>
                            </div>
                        </div>
                    </div>
                </div>*@

        </div>

        <div style="padding-top:0px" class="row">
            <label asp-for="targetScore" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8" data-step="3" data-intro="Set pass score for this test">
                <input asp-for="targetScore" type="number" class="form-control" id="score">
                <span asp-validation-for="targetScore" class="text-danger"></span>
            </div>
        </div>
        <div style="padding-top:5px" class="row">
            <label asp-for="timer" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8" data-step="4" data-intro="Set timer (in seconds) for every question. Example: 75 means 1 minute and 15 seconds">
                <input asp-for="timer" type="number" class="form-control" id="timer">
                <span asp-validation-for="timer" class="text-danger"></span>
            </div>
        </div>
        <div style="padding-top:5px" class="row">
            <label asp-for="status" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8 my-2">
                <div class="pretty p-success p-switch p-fill" data-step="5" data-intro="Turn it on so that the user can take your test ">
                    <input asp-for="status" type="checkbox" /> @*@Html.DisplayNameFor(model => model.status)*@
                    <div class="state p-success">
                        <label></label>
                    </div>
                </div>
            </div>
        </div>
        <div style="padding-top:5px" class="row">
            <label asp-for="showResult" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8 my-2">
                <div class="pretty p-success p-switch p-fill" data-step="6" data-intro="Turn it on if you would like to let the user see the correct answer after they finish their test ">
                    <input asp-for="showResult" type="checkbox" /> @*@Html.DisplayNameFor(model => model.status)*@
                    <div class="state p-success">
                        <label></label>
                    </div>
                </div>
            </div>
        </div>
        <div style="padding-top:5px" class="row">
            <label asp-for="ramdomizeOrderOfAnswer" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8 my-2">
                <div class="pretty p-success p-switch p-fill" data-step="7" data-intro="Turn it on if you would like to shuffle the order of answer">
                    <input asp-for="ramdomizeOrderOfAnswer" type="checkbox" /> @*@Html.DisplayNameFor(model => model.status)*@
                    <div class="state p-success">
                        <label></label>
                    </div>
                </div>
            </div>
        </div>
        <div style="padding-top:5px" class="row">
            <label asp-for="ramdomizeOrderOfQuestion" class="col-form-label col-sm-3"></label>
            <div class="col-sm-8 my-2">
                <div class="pretty p-success p-switch p-fill" data-step="8" data-intro="Turn it on if you would like to shuffle the order of question">
                    <input asp-for="ramdomizeOrderOfQuestion" type="checkbox" /> @*@Html.DisplayNameFor(model => model.status)*@
                    <div class="state p-success">
                        <label></label>
                    </div>
                </div>
            </div>
        </div>


        <div class=" col-sm-offset-2 col-sm-8" style="text-align:center">
            <button data-step="9" data-intro="Click save to complete" type="submit" value="Create" class="  btn btn-outline-primary">Save</button>
            <button class="btn btn-outline-warning" asp-action="Index">Cancel</button>
        </div>
    </form>
</div>


@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @*<script src="~/lib/momentjs/moment.min.js"></script>
    @*<script src="~/lib/momentjs/moment-with-locales.min.js"></script>
    <script src="~/lib/tempusdominus/tempusdominus.min.js"></script>*@
    <script type="text/javascript">

        $(document).ready(function () {

            $('#help').click(function () {
                console.log('ok');
                introJs().start();
            });

            $(function () {
                $('#datetimepicker5').datepicker({
                    uiLibrary: 'bootstrap4',
                    calendarWeeks: true,
                    disableDaysOfWeek: [0],
                    keyboardNavigation: true,
                    showOtherMonths: true
                });
                //$('#datetimepicker5').datetimepicker({

                //    format: 'L',
                //    defaultDate: "12/01/2019",
                //    icons: {
                //        //time: "fa fa-clock",
                //        date: "fa calendar-alt",
                //        up: "fa fa-arrow-up",
                //        down: "fa fa-arrow-down"

                //    },
                //    daysOfWeekDisabled: [0],
                //    //sideBySide: true,

                //});

                $('#datetimepicker5').keypress(function (event) {
                    if (event.keyCode === 10 || event.keyCode === 13) {
                        event.preventDefault();
                    }
                });
            });



        });

    </script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
}

qa8/Views/Quiz/Deadline.cshtml
@model qa8.Models.Quiz
@{
    ViewData["Title"] = "Q&A System";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var active = Model.status;
 
}

<h2 class="text-danger" style="text-align:center">Error page </h2>
<h3>
    This Quiz : "@Html.DisplayFor(model => model.text)" is set to private by Administrator or you was late !<br />

    Deadline on @Html.DisplayFor(model => model.deadLine)<br />
    Status : @Html.DisplayFor(model => model.status) 
</h3>

qa8/Views/Quiz/DeleteError.cshtml
@{
    ViewData["Title"] = "Q&A System";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-danger">You can not do this action. This test do not belong to you !</h2>
<div style="text-align:center">
    <a class="btn btn-outline-primary" asp-controller="Quiz" asp-action="Index">Go back</a>
</div>

qa8/Views/Quiz/NotForYou.cshtml
@model qa8.Models.Quiz
@{
    ViewData["Title"] = "Q&A System";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var active = Model.status;
 
}

<h2 class="text-danger" style="text-align:center">Error page </h2>
<h3>
    This test : "@Html.DisplayFor(model => model.text)" is not for you !<br />
    Please provide your ID card number to administrator if you want to take part in this test !
</h3>
<div style="text-align:center">
    <a class="btn btn-outline-primary" asp-controller="Quiz" asp-action="SelectQuiz">Go back</a>

</div>

qa8/Views/Quiz/ParticipantsList.cshtml
@model qa8.Models.Quiz
@{
    ViewData["Title"] = "Q&A System";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-success" style="text-align:center">Participants management page</h2>
<div>
    <form class="form-horizontal col-sm-6">
        @*<div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.id)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.id)">
            </div>
        </div>*@
        <div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.text)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.text)">
            </div>
        </div>
        @*<div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.authorId)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.authorId)">
            </div>
        </div>*@
        @*<div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.deadLine)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.deadLine)">
            </div>
        </div>*@
        @*<div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.targetScore)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.targetScore)">
            </div>
        </div>*@
        @*<div class="form-group row">
            <label class="col-form-label col-sm-3">@Html.DisplayNameFor(model => model.timer)</label>
            <div class="col-sm-8">
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.timer)">
            </div>
        </div>*@
    </form>
</div>
<div>
    <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@Model.id">Test setting</a> |
    <a class="btn btn-outline-primary" asp-action="Index">Back to test editor</a>
</div>

<hr />


<p>
        <a class="btn btn-outline-primary " asp-controller="Participant" asp-action="Create" asp-route-quizId="@Model.id">Add participant</a>
    </p>
@*<div>
    @Html.RenderPartialAsync("~/Views/Participant/Create.cshtml", new Participant { quizId = Model.id });
</div>*@

<table class="table">
    <thead>
        <tr>
            <th>
                Code
            </th>
            <th>
                Quiz ID
            </th>
            <th>
                ID Card No.
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.participants)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quizId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.userId)
                </td>
                <td>
                    @*<a class="btn btn-success glyphicon glyphicon-pencil" asp-controller="Participant" asp-action="Edit" asp-route-id="@item.id"></a> |
                        <a class="btn btn-success glyphicon glyphicon-eye-open" asp-action="Details" asp-route-id="@item.id"></a> |*@
                    <a class="btn btn-outline-danger fa fa-trash-alt" asp-controller="Participant" asp-action="Delete" asp-route-id="@item.id"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

qa8/Views/Quiz/QuizDetailsError.cshtml
@{
    ViewData["Title"] = "Q&A System";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-danger" style="text-align:center">Error page </h2>
<h3>
    There are not any response for this test
</h3>